global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-email'
  routes:
    - match:
        severity: critical
      receiver: 'team-pager'
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: 'team-email'
      repeat_interval: 12h

receivers:
  - name: 'team-email'
    email_configs:
      - to: 'team@example.com'
        send_resolved: true
        headers:
          subject: '{{ template "email.subject" . }}'
        html: '{{ template "email.html" . }}'

  - name: 'team-pager'
    email_configs:
      - to: 'oncall@example.com'
        send_resolved: true
        headers:
          subject: '[CRITICAL] {{ template "email.subject" . }}'
        html: '{{ template "email.html" . }}'
    webhook_configs:
      - url: 'http://pagerduty-webhook:8080/notify'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

templates:
  - name: 'email.subject'
    template: |
      [{{ .Status | toUpper }}] {{ .GroupLabels.alertname }} - {{ .CommonAnnotations.summary }}

  - name: 'email.html'
    template: |
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; }
          .alert { padding: 15px; margin-bottom: 20px; border: 1px solid transparent; border-radius: 4px; }
          .critical { background-color: #f2dede; border-color: #ebccd1; color: #a94442; }
          .warning { background-color: #fcf8e3; border-color: #faebcc; color: #8a6d3b; }
          .resolved { background-color: #dff0d8; border-color: #d6e9c6; color: #3c763d; }
        </style>
      </head>
      <body>
        <div class="alert {{ if eq .Status "firing" }}{{ if eq .CommonLabels.severity "critical" }}critical{{ else }}warning{{ end }}{{ else }}resolved{{ end }}">
          <h3>{{ .GroupLabels.alertname }}</h3>
          <p><strong>Status:</strong> {{ .Status | toUpper }}</p>
          <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          {{ if .CommonAnnotations.runbook_url }}
          <p><strong>Runbook:</strong> <a href="{{ .CommonAnnotations.runbook_url }}">View Runbook</a></p>
          {{ end }}
          <h4>Alerts:</h4>
          <ul>
          {{ range .Alerts }}
            <li>
              <strong>Started:</strong> {{ .StartsAt }}<br>
              <strong>Labels:</strong><br>
              <ul>
                {{ range .Labels.SortedPairs }}
                  <li>{{ .Name }}: {{ .Value }}</li>
                {{ end }}
              </ul>
            </li>
          {{ end }}
          </ul>
        </div>
      </body>
      </html>
